---
title: "Development Economics: Project Data Preparation"
output:
  pdf_document: 
    toc: true
    fig_caption: yes
---
\newpage

```{r library_setup, results=FALSE, warning=FALSE, message=FALSE, echo=FALSE}
rm(list=ls())
require(tinytex) #LaTeX
require(ggplot2) #plots
require(haven) #load data
require(dplyr) #data management
require(lubridate) #data dates management
require(zoo) #for lagging
require(jtools) #tables
require(huxtable) #tables
require(lmtest) #reg tests
require(data.table) #for data filtering
require(sandwich) #regression errors
require(readxl) #for reading excel data
require(tidyr) #data
require(tidyverse) #data
require(did) #DiD (support staggered treatment)
require(panelView) #for panel data treatment visibility

getwd()
setwd("...") 
set.seed((123))

```



# Data

## Loading Drought Data
```{r drought load, message=FALSE, warning=FALSE}

# Load SPEI index data
droughtdata1 = read.csv("drought_data_output/spei3_yearly_master.csv")
colnames(droughtdata1)[which(names(droughtdata1) == "avg_spei3")] <- "spei"

# Load VIH stress data
droughtdata2 = read.csv("drought_data_output/agri_stress_long.csv")
colnames(droughtdata2)[which(names(droughtdata2) == "PROVINCE")] <- "district"
colnames(droughtdata2)[which(names(droughtdata2) == "YEAR")] <-"year"
colnames(droughtdata2)[which(names(droughtdata2) == "DATA")] <- "agric_stress"

# Load drought dummy data
droughtdata3 = read.csv("drought_data_output/district_yearly_drought_treatment_long.csv")
colnames(droughtdata3)[which(names(droughtdata3) == "district_name")] <- "district"
colnames(droughtdata3)[which(names(droughtdata3) == "dummy_drought_consecutive")] <- "drought_dummy"

droughtdata = left_join(droughtdata1, droughtdata2, by=c("year","district"))
droughtdata = left_join(droughtdata, droughtdata3, by=c("year","district"))

# Load raw agriculture data
raw_agri_data = as.data.frame(read_xlsx("agriculture data/agri.xlsx"))

```

## Load Household Data
```{r hh data, message=FALSE, warning=FALSE}

# Load Household Survey Data 
household_data <- list()
years_to_load <- 2004:2023
for (year in years_to_load) {
  if (year <= 2014) {
    file_extension <- ".xls"
    read_function <- readxl::read_xls} else {
    file_extension <- ".xlsx"
    read_function <- readxl::read_xlsx}
  file_path <- file.path("household_data", paste0("Household-", year, file_extension))
  if (file.exists(file_path)) {
    loaded_data <- try(read_function(file_path), silent = TRUE)
    if (!inherits(loaded_data, "try-error")) {
      household_data[[as.character(year)]] <- loaded_data
      cat("Successfully loaded:", file_path, "\n")} else {
      warning(paste("Could not read", file_path, "- skipping. Error:", as.character(loaded_data)))
      }} else {
    warning(paste("File not found:", file_path, "- skipping."))}}
cat("\nProcess complete. All available Excel datasets have been loaded into the 'household_data' list.\n")
rm(loaded_data)

```


## Dealing with Names
```{r names, message=FALSE, warning=FALSE}

# Raw (Household) Data List
raw_data_list = household_data

# Variables change names through the years, so we must go through the excel sheets
#  and find all the different types of names variables have
name_map <- list(
  district = c("hh_02", "MARZ", "marz"),
  hh_size = c("members", "MEMBERS"),
  urban = c("settlement", "SETTLEMENT", "SETTLEME"),
  poverty = c("poverty", "POVERTY", "pov", "POV"),
  exp = c("expend", "EXPEND"),
  income = c("totincome", "TOTINCOME", "TOTINCOM"),
  fdcons = c("fdcons", "FDCONS"),
  fdpurch = c("fdpurch", "FDPURCH")) 

# There is an overlap of the variable name for agriculural income
# In some years, the variable is called y1_3drm.10, but in others it has a  
# different name. And in some, y1_3drm.10 exists but describes another variable.
# We thus need to change the name of those variables to select precisely agric
for (year in names(household_data)) {
  year_num <- as.integer(year)
  if (year_num >= 2015 & year_num <= 2018) {
    if (year_num == 2015) {
      household_data[[year]] <- household_data[[year]] %>%
        rename_with(~"agric_income_temp", .cols = matches("y1_3drm.13"))
    } else if (year_num %in% c(2016, 2017, 2018)) {
      household_data[[year]] <- household_data[[year]] %>%
        rename_with(~"agric_income_temp", .cols = matches("y1_3drm.3"))}
    household_data[[year]] <- household_data[[year]] %>%
      rename_with(~"income_child_ignore", .cols = matches("y1_3drm.10"))}}

name_map$agric_income <- c("y1_3amd.3.00", "y1_3drm.10", "agric_income_temp")

# Fix the different names and set common ones established above
cleaned_data_list <- list()
final_columns <- names(name_map)
for (year in names(household_data)) {
  yearly_data <- household_data[[year]]
  current_names <- names(yearly_data)
  for (standard_name in names(name_map)) {
    possible_old_names <- name_map[[standard_name]]
    name_to_replace <- intersect(possible_old_names, current_names)
    if (length(name_to_replace) > 0) {
      yearly_data <- rename(yearly_data, !!standard_name := all_of(name_to_replace))}}
    yearly_data <- yearly_data %>%
    mutate(year = as.integer(year)) %>%
    select(year, any_of(final_columns))
    cleaned_data_list[[year]] <- yearly_data}

# Merge the different years
hh_dataset <- bind_rows(cleaned_data_list)

# Rename the districts according to their codes and set common ones
hh_dataset <- hh_dataset %>%
  mutate(district = case_when(
    district == "Yerevan"  ~ "Yerevan",
    district == "Aragatsotn"  ~ "Aragatsotn",
    district == "Ararat"  ~ "Ararat",
    district == "Armavir"  ~ "Armavir",
    district == "Gegharkunik"  ~ "Gegharkunik",
    district == "Lor"  ~ "Lor",
    district == "Kotayk"  ~ "Kotayk",
    district == "Shirak"  ~ "Shirak",
    district == "Syunik"  ~ "Syunik",
    district == "Vayots dzor" ~ "Vayots dzor",
    district == "Tavush" ~ "Tavush",
    district == 1  ~ "Yerevan",
    district == 2  ~ "Aragatsotn",
    district == 3  ~ "Ararat",
    district == 4  ~ "Armavir",
    district == 5  ~ "Gegharkunik",
    district == 6  ~ "Lor",
    district == 7  ~ "Kotayk",
    district == 8  ~ "Shirak",
    district == 9  ~ "Syunik",
    district == 10 ~ "Vayots dzor",
    district == 11 ~ "Tavush",
    district == "TAVUSH" ~ "Tavush",
    district == "YEREVAN" ~ "Yerevan",
    district == "ARAGATSOT" ~ "Aragtsotn",
    district == "ARARAT" ~ "Ararat",
    district == "ARMAVIR" ~ "Armavir",
    district == "GEGHARKUNIK" ~ "Gegharkunik",
    district == "KOTAYK" ~ "Kotayk",
    district == "SHIRAK" ~ "Shirak",
    district == "SYUNIK" ~ "Syunik",
    district == "VAYOTS DZOR" ~ "Vayots dzor",
    district == "LORI" ~ "Lor",
    district == "Lori" ~ "Lor",
    district == "rural" ~ "Armavir",
    district == "Sjunik" ~ "Syunik",
    district == "Vayots Dzor" ~ "Vayots dzor",
    district == "other urban" ~ "Yerevan",
    TRUE ~ NA_character_ ))

# Change poverty level for a dummy variable
hh_dataset <- hh_dataset %>%
  mutate(poverty = case_when(
    poverty == 1  ~ 0,
    poverty == 2  ~ 1,
    poverty == 3  ~ 1,
    TRUE ~ NA_real_))

# Change settlement values for a dummy variable (urbanization)
hh_dataset <- hh_dataset %>%
  mutate(urban = case_when(
    year <= 2017 & urban == 0 ~ 1,
    year <= 2017 & urban == 1 ~ 1,
    year <= 2017 & urban == 2 ~ 0,
    year %in% c(2018,2020) & urban == 1 ~ 1,
    year %in% c(2018,2020) & urban == 2 ~ 1,
    year %in% c(2018,2020) & urban == 3 ~ 0,
    year %in% c(2019,2021) & urban == 1 ~ 1,
    year %in% c(2019,2021) & urban == 2 ~ 0,
    year %in% c(2019,2021) & urban == 1 ~ 1,
    year >= 2022 & urban == 1 ~ 1,
    year >= 2022 & urban == 2 ~ 0,
    year >= 2022 & urban == -999999999 ~ NA_real_,
    TRUE ~ NA_real_ ))

```

```{r agric data, message=FALSE, warning=FALSE}

# Harmonize the dataset by linking year, district and agricultural variables
colnames(raw_agri_data) <- raw_agri_data[3, ]  
districts_row <- as.character(raw_agri_data[2, ])

# Associate agricultural variables with their districts (with a forward fill)
districts_filled <- fill(data.frame(district = districts_row), district, .direction = "down")$district
raw_agri_data[2, ] <- districts_filled
raw_agri_data <- raw_agri_data[-c(1, 3, 22:40), ] # Cut empty row

# Extract district names
districts_row <- as.character(raw_agri_data[1, -1])  
data_only <- raw_agri_data[-1, ]
clean_colnames <- gsub("\\.\\d+$", "", colnames(data_only)) # harmonize variables names

# Create a new dataset for row binding the observation in an appropriate way
stacked_data <- data.frame()

for (i in 2:ncol(data_only)) {
  temp_df <- data.frame(
    district = districts_row[i-1],
    year = data_only[[1]],
    variable = clean_colnames[i],
    value = as.numeric(data_only[[i]]),
    stringsAsFactors = FALSE
  )
  stacked_data <- rbind(stacked_data, temp_df)
}

# Pivot in order to put variables as a columns 
agric_data <- stacked_data %>%
  pivot_wider(
    names_from = variable,
    values_from = value
  ) %>%
  arrange(district, year)

# Harmonize district names with other dataset
agric_data <- agric_data %>%
  mutate(district = case_when(
    district == "Yerevan City"  ~ "Yerevan",
    district == "Aragatsotn Marz"  ~ "Aragatsotn",
    district == "Ararat Marz"  ~ "Ararat",
    district == "Armavir Marz"  ~ "Armavir",
    district == "Gegharkunik Marz"  ~ "Gegharkunik",
    district == "Lori Marz"  ~ "Lor",
    district == "Kotayk Marz"  ~ "Kotayk",
    district == "Shirak Marz"  ~ "Shirak",
    district == "Syunik Marz"  ~ "Syunik",
    district == "Vayots Dzor Marz" ~ "Vayots dzor",
    district == "Tavush Marz" ~ "Tavush")) 

#Withdraw some variables
agric_data = agric_data %>%
  select(-c(12:17)) %>%
  slice(-c(109:126))

# Replace ".." and "-" observations by NA
agric_data[agric_data == ".."] <- NA
agric_data[agric_data == "-"] <- NA


```

## Merging and Aggregating
```{r merges, message=FALSE, warning=FALSE}

# Household-level dataset is ready
hh_dataset = hh_dataset 

# District-level dataset by aggregating HH data
dataset <- hh_dataset %>%
  group_by(district, year) %>%
  summarise(income = mean(income), poverty = mean(poverty),
            exp = mean(exp), fdcons = mean(fdcons), fdpurch = mean(fdpurch),
              agric_income = mean(agric_income, na.rm=T), urban = mean(urban), n_households = n()) 

# Split income into deciles, i.e. assign each HH to an income decile with dummies
dataset_deciles <- hh_dataset %>%
  group_by(year) %>%
  mutate(national_decile = ntile(income, 10)) %>%
  ungroup() %>%
  group_by(district, year, national_decile) %>%
    summarise(income = mean(income), poverty = mean(poverty),
              exp = mean(exp), fdcons = mean(fdcons), fdpurch = mean(fdpurch),
              agric_income = mean(agric_income, na.rm=T), urban = mean(urban), n_households = n())

# Split income into deciles, i.e. assign each HH to an income decile with dummies
dataset_quartiles <- hh_dataset %>%
  group_by(year) %>%
  mutate(national_quartile = ntile(income, 4)) %>%
  ungroup() %>%
  group_by(district, year, national_quartile) %>%
    summarise(income = mean(income), poverty = mean(poverty),
              exp = mean(exp), fdcons = mean(fdcons), fdpurch = mean(fdpurch),
              agric_income = mean(agric_income, na.rm=T), urban = mean(urban), n_households = n())
 

# Add drought data 
dataset <- left_join(dataset, droughtdata, by = c("year", "district"))

dataset_deciles <- left_join(dataset_deciles, droughtdata, by = c("year", "district"))

dataset_quartiles <- left_join(dataset_quartiles, droughtdata, by = c("year", "district"))

hh_dataset <- left_join(hh_dataset, droughtdata, by = c("year", "district"))

# Add agriculture data
agric_data$year = as.integer(agric_data$year)
dataset = left_join(dataset, agric_data, by = c("year", "district"))

# Clean useless dataset
rm(cleaned_data_list, household_data, name_map, yearly_data, droughtdata, raw_agri_data, stacked_data, temp_df, data_only, agric_data)

# Replace Yerevan NA with 0
dataset <- dataset %>% mutate(agric_income = case_when(district == "Yerevan" & year == "2016" & is.na(agric_income) ~ 0, TRUE ~ agric_income))

# Change long names
colnames(dataset)[colnames(dataset) == "Gross  agricultural  output, total"] <- 'agric_output'

# Add all crop-related agricultural output variables
dataset$crops_output = dataset$`Gross harvest of  potatoes` + dataset$`Gross harvest of fruits and berries` + dataset$`Gross harvest of grains and leguminous plants`+ dataset$`Gross harvest of vegetables`

```

## Additional data
```{r watersupply}

marz_rename_map <- c(
  "Yerevan city" = "Yerevan",
  "Lory Marz" = "Lor",
  "Kotayk Marz" = "Kotayk",
  "Shirak Marz" = "Shirak",
  "Tavush Marz" = "Tavush",
  "Vayots Dzor Marz" = "Vayots dzor",
  "Syunik Marz" = "Syunik",
  "Gegharkunuk Marz" = "Gegharkunik",
  "Ararat Marz" = "Ararat",
  "Armavir Marz" = "Armavir",
  "Aragatsotn Marz" = "Aragatsotn")

watersupply <- read_excel("drought_data_output/watersupply.xlsx", skip = 2, col_names = FALSE)
new_headers <- as.character(watersupply[1, ])
new_headers[1] <- "Marz_Full"
new_headers[2] <- "Junk_Column"
colnames(watersupply) <- new_headers
watersupply <- watersupply[3:13, ]
watersupply = watersupply[,-2]

watersupply <- watersupply %>%
  mutate(Marz = marz_rename_map[Marz_Full]) %>%
  pivot_longer(
    cols = `2010`:`2023`,
    names_to = "Year",
    values_to = "WaterSupply") %>%
  select(Marz, Year, WaterSupply) %>%
  mutate(Year = as.integer(Year))

watersupply$WaterSupply = as.numeric(watersupply$WaterSupply)
names(watersupply)[names(watersupply) == 'Year'] <- 'year'
names(watersupply)[names(watersupply) == 'Marz'] <- 'district'

dataset <- left_join(dataset, watersupply, by = c("year", "district"))

```

```{r rainfall data, eval=TRUE, include=FALSE}

rainfalldata = read_csv("drought_data_output/rain_adm1_data.csv")
rainfalldata$difference = rainfalldata$Data - rainfalldata$Data_long_term_Average
#rainfalldata = subset(rainfalldata, Year >= 2010 & Year < 2024)
colnames(rainfalldata)[colnames(rainfalldata) == 'Province'] <- 'district'
colnames(rainfalldata)[colnames(rainfalldata) == 'Year'] <- 'year'
rainfalldata <- rainfalldata %>%
  group_by(district, year) %>%
  summarise(Total_Rainfall = sum(Data), Total_Rainfall_Diff = sum(difference)) %>%
  mutate(district = case_when(
    district == "Lori" ~ "Lor",
    district == "Vayots Dzor" ~ "Vayots dzor",
    district == "Gergharkunik" ~ "Gegharkunik", TRUE ~ district))

dataset <- left_join(dataset, rainfalldata, by = c("year", "district"))

```

## Treatment Lags
```{r lags}

#building lags
dataset <- dataset %>%
    arrange(district, year) %>%
    group_by(district) %>%
  mutate(
    drought_dummy_lag1 = lag(drought_dummy, n = 1, default = 0),
    drought_dummy_lag2 = lag(drought_dummy, n = 2, default = 0),
    spei_lag1 = lag(spei, n = 1, default = 0),
    spei_lag2 = lag(spei, n = 2, default = 0),
    share_lag1 = lag(share, n = 1, default = 0),
    share_lag2 = lag(share, n = 2, default = 0),
    agric_stress_lag1 = lag(agric_stress, n = 1, default = 0),
    agric_stress_lag2 = lag(agric_stress, n = 2, default = 0) ) %>%
    ungroup()

dataset_deciles <- dataset_deciles %>%
    arrange(district, year) %>%
    group_by(district) %>%
  mutate(
    drought_dummy_lag1 = lag(drought_dummy, n = 1, default = 0),
    drought_dummy_lag2 = lag(drought_dummy, n = 2, default = 0),
    spei_lag1 = lag(spei, n = 1, default = 0),
    spei_lag2 = lag(spei, n = 2, default = 0),
    share_lag1 = lag(share, n = 1, default = 0),
    share_lag2 = lag(share, n = 2, default = 0),
    agric_stress_lag1 = lag(agric_stress, n = 1, default = 0),
    agric_stress_lag2 = lag(agric_stress, n = 2, default = 0) ) %>%
    ungroup()

dataset_quartiles <- dataset_quartiles %>%
    arrange(district, year) %>%
    group_by(district) %>%
  mutate(
    drought_dummy_lag1 = lag(drought_dummy, n = 1, default = 0),
    drought_dummy_lag2 = lag(drought_dummy, n = 2, default = 0),
    spei_lag1 = lag(spei, n = 1, default = 0),
    spei_lag2 = lag(spei, n = 2, default = 0),
    share_lag1 = lag(share, n = 1, default = 0),
    share_lag2 = lag(share, n = 2, default = 0),
    agric_stress_lag1 = lag(agric_stress, n = 1, default = 0),
    agric_stress_lag2 = lag(agric_stress, n = 2, default = 0) ) %>%
    ungroup()

hh_dataset <- hh_dataset %>%
    arrange(district, year) %>%
    group_by(district) %>%
  mutate(
    drought_dummy_lag1 = lag(drought_dummy, n = 1, default = 0),
    drought_dummy_lag2 = lag(drought_dummy, n = 2, default = 0),
    spei_lag1 = lag(spei, n = 1, default = 0),
    spei_lag2 = lag(spei, n = 2, default = 0),
    share_lag1 = lag(share, n = 1, default = 0),
    share_lag2 = lag(share, n = 2, default = 0),
    agric_stress_lag1 = lag(agric_stress, n = 1, default = 0),
    agric_stress_lag2 = lag(agric_stress, n = 2, default = 0) ) %>%
    ungroup()

```

```{r check & save}

# One by one, for each column, check if there are NA  
#any(is.na(dataset$agric_income))

# Find which rows have the NAs, if any found above
#dataset[is.na(dataset$fdcons), ]

# Save
save(dataset, file = "final_data.Rdata")
save(dataset_deciles, file = "final_data_deciles.Rdata")
save(dataset_quartiles, file = "final_data_quartiles.Rdata")
save(hh_dataset, file = "final_data_household.Rdata")

```





















